/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

module.exports = {
  "series":[
    {
      "name":"Les Miserables",
      "type":"graph",
      "layout":"none",
      "data":[
        {
          "id":"0",
          "name":"Myriel",
          "label":{
            "normal":{
              "formatter":"Myriel",
              "show":false
            }
          },
          "symbolSize":28.685715,
          "x":-266.82776,
          "y":299.6904,
          "attributes":{
            "modularity_class":0
          },
          "value":28.685715,
          "category":0
        },
        {
          "id":"1",
          "name":"Napoleon",
          "label":{
            "normal":{
              "formatter":"Napoleon",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-418.08344,
          "y":446.8853,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"2",
          "name":"MlleBaptistine",
          "label":{
            "normal":{
              "formatter":"MlleBaptistine",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":-212.76357,
          "y":245.29176,
          "attributes":{
            "modularity_class":1
          },
          "value":9.485714,
          "category":1
        },
        {
          "id":"3",
          "name":"MmeMagloire",
          "label":{
            "normal":{
              "formatter":"MmeMagloire",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":-242.82404,
          "y":235.26283,
          "attributes":{
            "modularity_class":1
          },
          "value":9.485714,
          "category":1
        },
        {
          "id":"4",
          "name":"CountessDeLo",
          "label":{
            "normal":{
              "formatter":"CountessDeLo",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-379.30386,
          "y":429.06424,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"5",
          "name":"Geborand",
          "label":{
            "normal":{
              "formatter":"Geborand",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-417.26337,
          "y":406.03506,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"6",
          "name":"Champtercier",
          "label":{
            "normal":{
              "formatter":"Champtercier",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-332.6012,
          "y":485.16974,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"7",
          "name":"Cravatte",
          "label":{
            "normal":{
              "formatter":"Cravatte",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-382.69568,
          "y":475.09113,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"8",
          "name":"Count",
          "label":{
            "normal":{
              "formatter":"Count",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-320.384,
          "y":387.17325,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"9",
          "name":"OldMan",
          "label":{
            "normal":{
              "formatter":"OldMan",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-344.39832,
          "y":451.16772,
          "attributes":{
            "modularity_class":0
          },
          "value":4,
          "category":0
        },
        {
          "id":"10",
          "name":"Labarre",
          "label":{
            "normal":{
              "formatter":"Labarre",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-89.34107,
          "y":234.56128,
          "attributes":{
            "modularity_class":1
          },
          "value":4,
          "category":1
        },
        {
          "id":"11",
          "name":"Valjean",
          "label":{
            "normal":{
              "formatter":"Valjean",
              "show":  false
            }
          },
          "symbolSize":100,
          "x":-87.93029,
          "y":-6.8120565,
          "attributes":{
            "modularity_class":1
          },
          "value":100,
          "category":1
        },
        {
          "id":"12",
          "name":"Marguerite",
          "label":{
            "normal":{
              "formatter":"Marguerite",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":-339.77908,
          "y":-184.69139,
          "attributes":{
            "modularity_class":1
          },
          "value":6.742859,
          "category":1
        },
        {
          "id":"13",
          "name":"MmeDeR",
          "label":{
            "normal":{
              "formatter":"MmeDeR",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-194.31313,
          "y":178.55301,
          "attributes":{
            "modularity_class":1
          },
          "value":4,
          "category":1
        },
        {
          "id":"14",
          "name":"Isabeau",
          "label":{
            "normal":{
              "formatter":"Isabeau",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-158.05168,
          "y":201.99768,
          "attributes":{
            "modularity_class":1
          },
          "value":4,
          "category":1
        },
        {
          "id":"15",
          "name":"Gervais",
          "label":{
            "normal":{
              "formatter":"Gervais",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-127.701546,
          "y":242.55057,
          "attributes":{
            "modularity_class":1
          },
          "value":4,
          "category":1
        },
        {
          "id":"16",
          "name":"Tholomyes",
          "label":{
            "normal":{
              "formatter":"Tholomyes",
              "show":false
            }
          },
          "symbolSize":25.942856,
          "x":-385.2226,
          "y":-393.5572,
          "attributes":{
            "modularity_class":2
          },
          "value":25.942856,
          "category":2
        },
        {
          "id":"17",
          "name":"Listolier",
          "label":{
            "normal":{
              "formatter":"Listolier",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-516.55884,
          "y":-393.98975,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"18",
          "name":"Fameuil",
          "label":{
            "normal":{
              "formatter":"Fameuil",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-464.79382,
          "y":-493.57944,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"19",
          "name":"Blacheville",
          "label":{
            "normal":{
              "formatter":"Blacheville",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-515.1624,
          "y":-456.9891,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"20",
          "name":"Favourite",
          "label":{
            "normal":{
              "formatter":"Favourite",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-408.12122,
          "y":-464.5048,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"21",
          "name":"Dahlia",
          "label":{
            "normal":{
              "formatter":"Dahlia",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-456.44113,
          "y":-425.13303,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"22",
          "name":"Zephine",
          "label":{
            "normal":{
              "formatter":"Zephine",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":-459.1107,
          "y":-362.5133,
          "attributes":{
            "modularity_class":2
          },
          "value":20.457146,
          "category":2
        },
        {
          "id":"23",
          "name":"Fantine",
          "label":{
            "normal":{
              "formatter":"Fantine",
              "show":  false
            }
          },
          "symbolSize":42.4,
          "x":-313.42786,
          "y":-289.44803,
          "attributes":{
            "modularity_class":2
          },
          "value":42.4,
          "category":2
        },
        {
          "id":"24",
          "name":"MmeThenardier",
          "label":{
            "normal":{
              "formatter":"MmeThenardier",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":4.6313396,
          "y":-273.8517,
          "attributes":{
            "modularity_class":7
          },
          "value":31.428574,
          "category":7
        },
        {
          "id":"25",
          "name":"Thenardier",
          "label":{
            "normal":{
              "formatter":"Thenardier",
              "show":  false
            }
          },
          "symbolSize":45.142853,
          "x":82.80825,
          "y":-203.1144,
          "attributes":{
            "modularity_class":7
          },
          "value":45.142853,
          "category":7
        },
        {
          "id":"26",
          "name":"Cosette",
          "label":{
            "normal":{
              "formatter":"Cosette",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":78.64646,
          "y":-31.512747,
          "attributes":{
            "modularity_class":6
          },
          "value":31.428574,
          "category":6
        },
        {
          "id":"27",
          "name":"Javert",
          "label":{
            "normal":{
              "formatter":"Javert",
              "show":  false
            }
          },
          "symbolSize":47.88571,
          "x":-81.46074,
          "y":-204.20204,
          "attributes":{
            "modularity_class":7
          },
          "value":47.88571,
          "category":7
        },
        {
          "id":"28",
          "name":"Fauchelevent",
          "label":{
            "normal":{
              "formatter":"Fauchelevent",
              "show":false
            }
          },
          "symbolSize":12.228573,
          "x":-225.73984,
          "y":82.41631,
          "attributes":{
            "modularity_class":4
          },
          "value":12.228573,
          "category":4
        },
        {
          "id":"29",
          "name":"Bamatabois",
          "label":{
            "normal":{
              "formatter":"Bamatabois",
              "show":false
            }
          },
          "symbolSize":23.2,
          "x":-385.6842,
          "y":-20.206686,
          "attributes":{
            "modularity_class":3
          },
          "value":23.2,
          "category":3
        },
        {
          "id":"30",
          "name":"Perpetue",
          "label":{
            "normal":{
              "formatter":"Perpetue",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":-403.92447,
          "y":-197.69823,
          "attributes":{
            "modularity_class":2
          },
          "value":6.742859,
          "category":2
        },
        {
          "id":"31",
          "name":"Simplice",
          "label":{
            "normal":{
              "formatter":"Simplice",
              "show":false
            }
          },
          "symbolSize":12.228573,
          "x":-281.4253,
          "y":-158.45137,
          "attributes":{
            "modularity_class":2
          },
          "value":12.228573,
          "category":2
        },
        {
          "id":"32",
          "name":"Scaufflaire",
          "label":{
            "normal":{
              "formatter":"Scaufflaire",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-122.41348,
          "y":210.37503,
          "attributes":{
            "modularity_class":1
          },
          "value":4,
          "category":1
        },
        {
          "id":"33",
          "name":"Woman1",
          "label":{
            "normal":{
              "formatter":"Woman1",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":-234.6001,
          "y":-113.15067,
          "attributes":{
            "modularity_class":1
          },
          "value":6.742859,
          "category":1
        },
        {
          "id":"34",
          "name":"Judge",
          "label":{
            "normal":{
              "formatter":"Judge",
              "show":false
            }
          },
          "symbolSize":17.714287,
          "x":-387.84915,
          "y":58.7059,
          "attributes":{
            "modularity_class":3
          },
          "value":17.714287,
          "category":3
        },
        {
          "id":"35",
          "name":"Champmathieu",
          "label":{
            "normal":{
              "formatter":"Champmathieu",
              "show":false
            }
          },
          "symbolSize":17.714287,
          "x":-338.2307,
          "y":87.48405,
          "attributes":{
            "modularity_class":3
          },
          "value":17.714287,
          "category":3
        },
        {
          "id":"36",
          "name":"Brevet",
          "label":{
            "normal":{
              "formatter":"Brevet",
              "show":false
            }
          },
          "symbolSize":17.714287,
          "x":-453.26874,
          "y":58.94648,
          "attributes":{
            "modularity_class":3
          },
          "value":17.714287,
          "category":3
        },
        {
          "id":"37",
          "name":"Chenildieu",
          "label":{
            "normal":{
              "formatter":"Chenildieu",
              "show":false
            }
          },
          "symbolSize":17.714287,
          "x":-386.44904,
          "y":140.05937,
          "attributes":{
            "modularity_class":3
          },
          "value":17.714287,
          "category":3
        },
        {
          "id":"38",
          "name":"Cochepaille",
          "label":{
            "normal":{
              "formatter":"Cochepaille",
              "show":false
            }
          },
          "symbolSize":17.714287,
          "x":-446.7876,
          "y":123.38005,
          "attributes":{
            "modularity_class":3
          },
          "value":17.714287,
          "category":3
        },
        {
          "id":"39",
          "name":"Pontmercy",
          "label":{
            "normal":{
              "formatter":"Pontmercy",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":336.49738,
          "y":-269.55914,
          "attributes":{
            "modularity_class":6
          },
          "value":9.485714,
          "category":6
        },
        {
          "id":"40",
          "name":"Boulatruelle",
          "label":{
            "normal":{
              "formatter":"Boulatruelle",
              "show":false
            }
          },
          "symbolSize":4,
          "x":29.187843,
          "y":-460.13132,
          "attributes":{
            "modularity_class":7
          },
          "value":4,
          "category":7
        },
        {
          "id":"41",
          "name":"Eponine",
          "label":{
            "normal":{
              "formatter":"Eponine",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":238.36697,
          "y":-210.00926,
          "attributes":{
            "modularity_class":7
          },
          "value":31.428574,
          "category":7
        },
        {
          "id":"42",
          "name":"Anzelma",
          "label":{
            "normal":{
              "formatter":"Anzelma",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":189.69513,
          "y":-346.50662,
          "attributes":{
            "modularity_class":7
          },
          "value":9.485714,
          "category":7
        },
        {
          "id":"43",
          "name":"Woman2",
          "label":{
            "normal":{
              "formatter":"Woman2",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":-187.00418,
          "y":-145.02663,
          "attributes":{
            "modularity_class":6
          },
          "value":9.485714,
          "category":6
        },
        {
          "id":"44",
          "name":"MotherInnocent",
          "label":{
            "normal":{
              "formatter":"MotherInnocent",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":-252.99521,
          "y":129.87549,
          "attributes":{
            "modularity_class":4
          },
          "value":6.742859,
          "category":4
        },
        {
          "id":"45",
          "name":"Gribier",
          "label":{
            "normal":{
              "formatter":"Gribier",
              "show":false
            }
          },
          "symbolSize":4,
          "x":-296.07935,
          "y":163.11964,
          "attributes":{
            "modularity_class":4
          },
          "value":4,
          "category":4
        },
        {
          "id":"46",
          "name":"Jondrette",
          "label":{
            "normal":{
              "formatter":"Jondrette",
              "show":false
            }
          },
          "symbolSize":4,
          "x":550.3201,
          "y":522.4031,
          "attributes":{
            "modularity_class":5
          },
          "value":4,
          "category":5
        },
        {
          "id":"47",
          "name":"MmeBurgon",
          "label":{
            "normal":{
              "formatter":"MmeBurgon",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":488.13535,
          "y":356.8573,
          "attributes":{
            "modularity_class":5
          },
          "value":6.742859,
          "category":5
        },
        {
          "id":"48",
          "name":"Gavroche",
          "label":{
            "normal":{
              "formatter":"Gavroche",
              "show":  false
            }
          },
          "symbolSize":61.600006,
          "x":387.89572,
          "y":110.462326,
          "attributes":{
            "modularity_class":8
          },
          "value":61.600006,
          "category":8
        },
        {
          "id":"49",
          "name":"Gillenormand",
          "label":{
            "normal":{
              "formatter":"Gillenormand",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":126.4831,
          "y":68.10622,
          "attributes":{
            "modularity_class":6
          },
          "value":20.457146,
          "category":6
        },
        {
          "id":"50",
          "name":"Magnon",
          "label":{
            "normal":{
              "formatter":"Magnon",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":127.07365,
          "y":-113.05923,
          "attributes":{
            "modularity_class":6
          },
          "value":6.742859,
          "category":6
        },
        {
          "id":"51",
          "name":"MlleGillenormand",
          "label":{
            "normal":{
              "formatter":"MlleGillenormand",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":162.63559,
          "y":117.6565,
          "attributes":{
            "modularity_class":6
          },
          "value":20.457146,
          "category":6
        },
        {
          "id":"52",
          "name":"MmePontmercy",
          "label":{
            "normal":{
              "formatter":"MmePontmercy",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":353.66415,
          "y":-205.89165,
          "attributes":{
            "modularity_class":6
          },
          "value":6.742859,
          "category":6
        },
        {
          "id":"53",
          "name":"MlleVaubois",
          "label":{
            "normal":{
              "formatter":"MlleVaubois",
              "show":false
            }
          },
          "symbolSize":4,
          "x":165.43939,
          "y":339.7736,
          "attributes":{
            "modularity_class":6
          },
          "value":4,
          "category":6
        },
        {
          "id":"54",
          "name":"LtGillenormand",
          "label":{
            "normal":{
              "formatter":"LtGillenormand",
              "show":false
            }
          },
          "symbolSize":12.228573,
          "x":137.69348,
          "y":196.1069,
          "attributes":{
            "modularity_class":6
          },
          "value":12.228573,
          "category":6
        },
        {
          "id":"55",
          "name":"Marius",
          "label":{
            "normal":{
              "formatter":"Marius",
              "show":  false
            }
          },
          "symbolSize":53.37143,
          "x":206.44687,
          "y":-13.805411,
          "attributes":{
            "modularity_class":6
          },
          "value":53.37143,
          "category":6
        },
        {
          "id":"56",
          "name":"BaronessT",
          "label":{
            "normal":{
              "formatter":"BaronessT",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":194.82993,
          "y":224.78036,
          "attributes":{
            "modularity_class":6
          },
          "value":6.742859,
          "category":6
        },
        {
          "id":"57",
          "name":"Mabeuf",
          "label":{
            "normal":{
              "formatter":"Mabeuf",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":597.6618,
          "y":135.18481,
          "attributes":{
            "modularity_class":8
          },
          "value":31.428574,
          "category":8
        },
        {
          "id":"58",
          "name":"Enjolras",
          "label":{
            "normal":{
              "formatter":"Enjolras",
              "show":  false
            }
          },
          "symbolSize":42.4,
          "x":355.78366,
          "y":-74.882454,
          "attributes":{
            "modularity_class":8
          },
          "value":42.4,
          "category":8
        },
        {
          "id":"59",
          "name":"Combeferre",
          "label":{
            "normal":{
              "formatter":"Combeferre",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":515.2961,
          "y":-46.167564,
          "attributes":{
            "modularity_class":8
          },
          "value":31.428574,
          "category":8
        },
        {
          "id":"60",
          "name":"Prouvaire",
          "label":{
            "normal":{
              "formatter":"Prouvaire",
              "show":false
            }
          },
          "symbolSize":25.942856,
          "x":614.29285,
          "y":-69.3104,
          "attributes":{
            "modularity_class":8
          },
          "value":25.942856,
          "category":8
        },
        {
          "id":"61",
          "name":"Feuilly",
          "label":{
            "normal":{
              "formatter":"Feuilly",
              "show":  false
            }
          },
          "symbolSize":31.428574,
          "x":550.1917,
          "y":-128.17537,
          "attributes":{
            "modularity_class":8
          },
          "value":31.428574,
          "category":8
        },
        {
          "id":"62",
          "name":"Courfeyrac",
          "label":{
            "normal":{
              "formatter":"Courfeyrac",
              "show":  false
            }
          },
          "symbolSize":36.91429,
          "x":436.17184,
          "y":-12.7286825,
          "attributes":{
            "modularity_class":8
          },
          "value":36.91429,
          "category":8
        },
        {
          "id":"63",
          "name":"Bahorel",
          "label":{
            "normal":{
              "formatter":"Bahorel",
              "show":  false
            }
          },
          "symbolSize":34.17143,
          "x":602.55225,
          "y":16.421427,
          "attributes":{
            "modularity_class":8
          },
          "value":34.17143,
          "category":8
        },
        {
          "id":"64",
          "name":"Bossuet",
          "label":{
            "normal":{
              "formatter":"Bossuet",
              "show":  false
            }
          },
          "symbolSize":36.91429,
          "x":455.81955,
          "y":-115.45826,
          "attributes":{
            "modularity_class":8
          },
          "value":36.91429,
          "category":8
        },
        {
          "id":"65",
          "name":"Joly",
          "label":{
            "normal":{
              "formatter":"Joly",
              "show":  false
            }
          },
          "symbolSize":34.17143,
          "x":516.40784,
          "y":47.242233,
          "attributes":{
            "modularity_class":8
          },
          "value":34.17143,
          "category":8
        },
        {
          "id":"66",
          "name":"Grantaire",
          "label":{
            "normal":{
              "formatter":"Grantaire",
              "show":false
            }
          },
          "symbolSize":28.685715,
          "x":646.4313,
          "y":-151.06331,
          "attributes":{
            "modularity_class":8
          },
          "value":28.685715,
          "category":8
        },
        {
          "id":"67",
          "name":"MotherPlutarch",
          "label":{
            "normal":{
              "formatter":"MotherPlutarch",
              "show":false
            }
          },
          "symbolSize":4,
          "x":668.9568,
          "y":204.65488,
          "attributes":{
            "modularity_class":8
          },
          "value":4,
          "category":8
        },
        {
          "id":"68",
          "name":"Gueulemer",
          "label":{
            "normal":{
              "formatter":"Gueulemer",
              "show":false
            }
          },
          "symbolSize":28.685715,
          "x":78.4799,
          "y":-347.15146,
          "attributes":{
            "modularity_class":7
          },
          "value":28.685715,
          "category":7
        },
        {
          "id":"69",
          "name":"Babet",
          "label":{
            "normal":{
              "formatter":"Babet",
              "show":false
            }
          },
          "symbolSize":28.685715,
          "x":150.35959,
          "y":-298.50797,
          "attributes":{
            "modularity_class":7
          },
          "value":28.685715,
          "category":7
        },
        {
          "id":"70",
          "name":"Claquesous",
          "label":{
            "normal":{
              "formatter":"Claquesous",
              "show":false
            }
          },
          "symbolSize":28.685715,
          "x":137.3717,
          "y":-410.2809,
          "attributes":{
            "modularity_class":7
          },
          "value":28.685715,
          "category":7
        },
        {
          "id":"71",
          "name":"Montparnasse",
          "label":{
            "normal":{
              "formatter":"Montparnasse",
              "show":false
            }
          },
          "symbolSize":25.942856,
          "x":234.87747,
          "y":-400.85983,
          "attributes":{
            "modularity_class":7
          },
          "value":25.942856,
          "category":7
        },
        {
          "id":"72",
          "name":"Toussaint",
          "label":{
            "normal":{
              "formatter":"Toussaint",
              "show":false
            }
          },
          "symbolSize":9.485714,
          "x":40.942253,
          "y":113.78272,
          "attributes":{
            "modularity_class":1
          },
          "value":9.485714,
          "category":1
        },
        {
          "id":"73",
          "name":"Child1",
          "label":{
            "normal":{
              "formatter":"Child1",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":437.939,
          "y":291.58234,
          "attributes":{
            "modularity_class":8
          },
          "value":6.742859,
          "category":8
        },
        {
          "id":"74",
          "name":"Child2",
          "label":{
            "normal":{
              "formatter":"Child2",
              "show":false
            }
          },
          "symbolSize":6.742859,
          "x":466.04922,
          "y":283.3606,
          "attributes":{
            "modularity_class":8
          },
          "value":6.742859,
          "category":8
        },
        {
          "id":"75",
          "name":"Brujon",
          "label":{
            "normal":{
              "formatter":"Brujon",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":238.79364,
          "y":-314.06345,
          "attributes":{
            "modularity_class":7
          },
          "value":20.457146,
          "category":7
        },
        {
          "id":"76",
          "name":"MmeHucheloup",
          "label":{
            "normal":{
              "formatter":"MmeHucheloup",
              "show":false
            }
          },
          "symbolSize":20.457146,
          "x":712.18353,
          "y":4.8131495,
          "attributes":{
            "modularity_class":8
          },
          "value":20.457146,
          "category":8
        }
      ],
      "links":[
        {
          "id":"0",
          "name":null,
          "source":"1",
          "target":"0"
        },
        {
          "id":"1",
          "name":null,
          "source":"2",
          "target":"0"
        },
        {
          "id":"2",
          "name":null,
          "source":"3",
          "target":"0"
        },
        {
          "id":"3",
          "name":null,
          "source":"3",
          "target":"2"
        },
        {
          "id":"4",
          "name":null,
          "source":"4",
          "target":"0"
        },
        {
          "id":"5",
          "name":null,
          "source":"5",
          "target":"0"
        },
        {
          "id":"6",
          "name":null,
          "source":"6",
          "target":"0"
        },
        {
          "id":"7",
          "name":null,
          "source":"7",
          "target":"0"
        },
        {
          "id":"8",
          "name":null,
          "source":"8",
          "target":"0"
        },
        {
          "id":"9",
          "name":null,
          "source":"9",
          "target":"0"
        },
        {
          "id":"13",
          "name":null,
          "source":"11",
          "target":"0"
        },
        {
          "id":null,
          "name":null,
          "source":"11",
          "target":"2"
        },
        {
          "id":"11",
          "name":null,
          "source":"11",
          "target":"3"
        },
        {
          "id":"10",
          "name":null,
          "source":"11",
          "target":"10"
        },
        {
          "id":"14",
          "name":null,
          "source":"12",
          "target":"11"
        },
        {
          "id":"15",
          "name":null,
          "source":"13",
          "target":"11"
        },
        {
          "id":"16",
          "name":null,
          "source":"14",
          "target":"11"
        },
        {
          "id":"17",
          "name":null,
          "source":"15",
          "target":"11"
        },
        {
          "id":"18",
          "name":null,
          "source":"17",
          "target":"16"
        },
        {
          "id":"19",
          "name":null,
          "source":"18",
          "target":"16"
        },
        {
          "id":"20",
          "name":null,
          "source":"18",
          "target":"17"
        },
        {
          "id":"21",
          "name":null,
          "source":"19",
          "target":"16"
        },
        {
          "id":"22",
          "name":null,
          "source":"19",
          "target":"17"
        },
        {
          "id":"23",
          "name":null,
          "source":"19",
          "target":"18"
        },
        {
          "id":"24",
          "name":null,
          "source":"20",
          "target":"16"
        },
        {
          "id":"25",
          "name":null,
          "source":"20",
          "target":"17"
        },
        {
          "id":"26",
          "name":null,
          "source":"20",
          "target":"18"
        },
        {
          "id":"27",
          "name":null,
          "source":"20",
          "target":"19"
        },
        {
          "id":"28",
          "name":null,
          "source":"21",
          "target":"16"
        },
        {
          "id":"29",
          "name":null,
          "source":"21",
          "target":"17"
        },
        {
          "id":"30",
          "name":null,
          "source":"21",
          "target":"18"
        },
        {
          "id":"31",
          "name":null,
          "source":"21",
          "target":"19"
        },
        {
          "id":"32",
          "name":null,
          "source":"21",
          "target":"20"
        },
        {
          "id":"33",
          "name":null,
          "source":"22",
          "target":"16"
        },
        {
          "id":"34",
          "name":null,
          "source":"22",
          "target":"17"
        },
        {
          "id":"35",
          "name":null,
          "source":"22",
          "target":"18"
        },
        {
          "id":"36",
          "name":null,
          "source":"22",
          "target":"19"
        },
        {
          "id":"37",
          "name":null,
          "source":"22",
          "target":"20"
        },
        {
          "id":"38",
          "name":null,
          "source":"22",
          "target":"21"
        },
        {
          "id":"47",
          "name":null,
          "source":"23",
          "target":"11"
        },
        {
          "id":"46",
          "name":null,
          "source":"23",
          "target":"12"
        },
        {
          "id":"39",
          "name":null,
          "source":"23",
          "target":"16"
        },
        {
          "id":"40",
          "name":null,
          "source":"23",
          "target":"17"
        },
        {
          "id":"41",
          "name":null,
          "source":"23",
          "target":"18"
        },
        {
          "id":"42",
          "name":null,
          "source":"23",
          "target":"19"
        },
        {
          "id":"43",
          "name":null,
          "source":"23",
          "target":"20"
        },
        {
          "id":"44",
          "name":null,
          "source":"23",
          "target":"21"
        },
        {
          "id":"45",
          "name":null,
          "source":"23",
          "target":"22"
        },
        {
          "id":null,
          "name":null,
          "source":"24",
          "target":"11"
        },
        {
          "id":"48",
          "name":null,
          "source":"24",
          "target":"23"
        },
        {
          "id":"52",
          "name":null,
          "source":"25",
          "target":"11"
        },
        {
          "id":"51",
          "name":null,
          "source":"25",
          "target":"23"
        },
        {
          "id":"50",
          "name":null,
          "source":"25",
          "target":"24"
        },
        {
          "id":null,
          "name":null,
          "source":"26",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"26",
          "target":"16"
        },
        {
          "id":"53",
          "name":null,
          "source":"26",
          "target":"24"
        },
        {
          "id":"56",
          "name":null,
          "source":"26",
          "target":"25"
        },
        {
          "id":"57",
          "name":null,
          "source":"27",
          "target":"11"
        },
        {
          "id":"58",
          "name":null,
          "source":"27",
          "target":"23"
        },
        {
          "id":null,
          "name":null,
          "source":"27",
          "target":"24"
        },
        {
          "id":"59",
          "name":null,
          "source":"27",
          "target":"25"
        },
        {
          "id":"61",
          "name":null,
          "source":"27",
          "target":"26"
        },
        {
          "id":"62",
          "name":null,
          "source":"28",
          "target":"11"
        },
        {
          "id":"63",
          "name":null,
          "source":"28",
          "target":"27"
        },
        {
          "id":"66",
          "name":null,
          "source":"29",
          "target":"11"
        },
        {
          "id":"64",
          "name":null,
          "source":"29",
          "target":"23"
        },
        {
          "id":"65",
          "name":null,
          "source":"29",
          "target":"27"
        },
        {
          "id":"67",
          "name":null,
          "source":"30",
          "target":"23"
        },
        {
          "id":null,
          "name":null,
          "source":"31",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"31",
          "target":"23"
        },
        {
          "id":null,
          "name":null,
          "source":"31",
          "target":"27"
        },
        {
          "id":"68",
          "name":null,
          "source":"31",
          "target":"30"
        },
        {
          "id":"72",
          "name":null,
          "source":"32",
          "target":"11"
        },
        {
          "id":"73",
          "name":null,
          "source":"33",
          "target":"11"
        },
        {
          "id":"74",
          "name":null,
          "source":"33",
          "target":"27"
        },
        {
          "id":"75",
          "name":null,
          "source":"34",
          "target":"11"
        },
        {
          "id":"76",
          "name":null,
          "source":"34",
          "target":"29"
        },
        {
          "id":"77",
          "name":null,
          "source":"35",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"35",
          "target":"29"
        },
        {
          "id":"78",
          "name":null,
          "source":"35",
          "target":"34"
        },
        {
          "id":"82",
          "name":null,
          "source":"36",
          "target":"11"
        },
        {
          "id":"83",
          "name":null,
          "source":"36",
          "target":"29"
        },
        {
          "id":"80",
          "name":null,
          "source":"36",
          "target":"34"
        },
        {
          "id":"81",
          "name":null,
          "source":"36",
          "target":"35"
        },
        {
          "id":"87",
          "name":null,
          "source":"37",
          "target":"11"
        },
        {
          "id":"88",
          "name":null,
          "source":"37",
          "target":"29"
        },
        {
          "id":"84",
          "name":null,
          "source":"37",
          "target":"34"
        },
        {
          "id":"85",
          "name":null,
          "source":"37",
          "target":"35"
        },
        {
          "id":"86",
          "name":null,
          "source":"37",
          "target":"36"
        },
        {
          "id":"93",
          "name":null,
          "source":"38",
          "target":"11"
        },
        {
          "id":"94",
          "name":null,
          "source":"38",
          "target":"29"
        },
        {
          "id":"89",
          "name":null,
          "source":"38",
          "target":"34"
        },
        {
          "id":"90",
          "name":null,
          "source":"38",
          "target":"35"
        },
        {
          "id":"91",
          "name":null,
          "source":"38",
          "target":"36"
        },
        {
          "id":"92",
          "name":null,
          "source":"38",
          "target":"37"
        },
        {
          "id":"95",
          "name":null,
          "source":"39",
          "target":"25"
        },
        {
          "id":"96",
          "name":null,
          "source":"40",
          "target":"25"
        },
        {
          "id":"97",
          "name":null,
          "source":"41",
          "target":"24"
        },
        {
          "id":"98",
          "name":null,
          "source":"41",
          "target":"25"
        },
        {
          "id":"101",
          "name":null,
          "source":"42",
          "target":"24"
        },
        {
          "id":"100",
          "name":null,
          "source":"42",
          "target":"25"
        },
        {
          "id":"99",
          "name":null,
          "source":"42",
          "target":"41"
        },
        {
          "id":"102",
          "name":null,
          "source":"43",
          "target":"11"
        },
        {
          "id":"103",
          "name":null,
          "source":"43",
          "target":"26"
        },
        {
          "id":"104",
          "name":null,
          "source":"43",
          "target":"27"
        },
        {
          "id":null,
          "name":null,
          "source":"44",
          "target":"11"
        },
        {
          "id":"105",
          "name":null,
          "source":"44",
          "target":"28"
        },
        {
          "id":"107",
          "name":null,
          "source":"45",
          "target":"28"
        },
        {
          "id":"108",
          "name":null,
          "source":"47",
          "target":"46"
        },
        {
          "id":"112",
          "name":null,
          "source":"48",
          "target":"11"
        },
        {
          "id":"110",
          "name":null,
          "source":"48",
          "target":"25"
        },
        {
          "id":"111",
          "name":null,
          "source":"48",
          "target":"27"
        },
        {
          "id":"109",
          "name":null,
          "source":"48",
          "target":"47"
        },
        {
          "id":null,
          "name":null,
          "source":"49",
          "target":"11"
        },
        {
          "id":"113",
          "name":null,
          "source":"49",
          "target":"26"
        },
        {
          "id":null,
          "name":null,
          "source":"50",
          "target":"24"
        },
        {
          "id":"115",
          "name":null,
          "source":"50",
          "target":"49"
        },
        {
          "id":"119",
          "name":null,
          "source":"51",
          "target":"11"
        },
        {
          "id":"118",
          "name":null,
          "source":"51",
          "target":"26"
        },
        {
          "id":"117",
          "name":null,
          "source":"51",
          "target":"49"
        },
        {
          "id":null,
          "name":null,
          "source":"52",
          "target":"39"
        },
        {
          "id":"120",
          "name":null,
          "source":"52",
          "target":"51"
        },
        {
          "id":"122",
          "name":null,
          "source":"53",
          "target":"51"
        },
        {
          "id":"125",
          "name":null,
          "source":"54",
          "target":"26"
        },
        {
          "id":"124",
          "name":null,
          "source":"54",
          "target":"49"
        },
        {
          "id":"123",
          "name":null,
          "source":"54",
          "target":"51"
        },
        {
          "id":"131",
          "name":null,
          "source":"55",
          "target":"11"
        },
        {
          "id":"132",
          "name":null,
          "source":"55",
          "target":"16"
        },
        {
          "id":"133",
          "name":null,
          "source":"55",
          "target":"25"
        },
        {
          "id":null,
          "name":null,
          "source":"55",
          "target":"26"
        },
        {
          "id":"128",
          "name":null,
          "source":"55",
          "target":"39"
        },
        {
          "id":"134",
          "name":null,
          "source":"55",
          "target":"41"
        },
        {
          "id":"135",
          "name":null,
          "source":"55",
          "target":"48"
        },
        {
          "id":"127",
          "name":null,
          "source":"55",
          "target":"49"
        },
        {
          "id":"126",
          "name":null,
          "source":"55",
          "target":"51"
        },
        {
          "id":"129",
          "name":null,
          "source":"55",
          "target":"54"
        },
        {
          "id":"136",
          "name":null,
          "source":"56",
          "target":"49"
        },
        {
          "id":"137",
          "name":null,
          "source":"56",
          "target":"55"
        },
        {
          "id":null,
          "name":null,
          "source":"57",
          "target":"41"
        },
        {
          "id":null,
          "name":null,
          "source":"57",
          "target":"48"
        },
        {
          "id":"138",
          "name":null,
          "source":"57",
          "target":"55"
        },
        {
          "id":"145",
          "name":null,
          "source":"58",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"58",
          "target":"27"
        },
        {
          "id":"142",
          "name":null,
          "source":"58",
          "target":"48"
        },
        {
          "id":"141",
          "name":null,
          "source":"58",
          "target":"55"
        },
        {
          "id":"144",
          "name":null,
          "source":"58",
          "target":"57"
        },
        {
          "id":"148",
          "name":null,
          "source":"59",
          "target":"48"
        },
        {
          "id":"147",
          "name":null,
          "source":"59",
          "target":"55"
        },
        {
          "id":null,
          "name":null,
          "source":"59",
          "target":"57"
        },
        {
          "id":"146",
          "name":null,
          "source":"59",
          "target":"58"
        },
        {
          "id":"150",
          "name":null,
          "source":"60",
          "target":"48"
        },
        {
          "id":"151",
          "name":null,
          "source":"60",
          "target":"58"
        },
        {
          "id":"152",
          "name":null,
          "source":"60",
          "target":"59"
        },
        {
          "id":"153",
          "name":null,
          "source":"61",
          "target":"48"
        },
        {
          "id":"158",
          "name":null,
          "source":"61",
          "target":"55"
        },
        {
          "id":"157",
          "name":null,
          "source":"61",
          "target":"57"
        },
        {
          "id":"154",
          "name":null,
          "source":"61",
          "target":"58"
        },
        {
          "id":"156",
          "name":null,
          "source":"61",
          "target":"59"
        },
        {
          "id":"155",
          "name":null,
          "source":"61",
          "target":"60"
        },
        {
          "id":"164",
          "name":null,
          "source":"62",
          "target":"41"
        },
        {
          "id":"162",
          "name":null,
          "source":"62",
          "target":"48"
        },
        {
          "id":"159",
          "name":null,
          "source":"62",
          "target":"55"
        },
        {
          "id":null,
          "name":null,
          "source":"62",
          "target":"57"
        },
        {
          "id":"160",
          "name":null,
          "source":"62",
          "target":"58"
        },
        {
          "id":"161",
          "name":null,
          "source":"62",
          "target":"59"
        },
        {
          "id":null,
          "name":null,
          "source":"62",
          "target":"60"
        },
        {
          "id":"165",
          "name":null,
          "source":"62",
          "target":"61"
        },
        {
          "id":null,
          "name":null,
          "source":"63",
          "target":"48"
        },
        {
          "id":"174",
          "name":null,
          "source":"63",
          "target":"55"
        },
        {
          "id":null,
          "name":null,
          "source":"63",
          "target":"57"
        },
        {
          "id":null,
          "name":null,
          "source":"63",
          "target":"58"
        },
        {
          "id":"167",
          "name":null,
          "source":"63",
          "target":"59"
        },
        {
          "id":null,
          "name":null,
          "source":"63",
          "target":"60"
        },
        {
          "id":"172",
          "name":null,
          "source":"63",
          "target":"61"
        },
        {
          "id":"169",
          "name":null,
          "source":"63",
          "target":"62"
        },
        {
          "id":"184",
          "name":null,
          "source":"64",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"64",
          "target":"48"
        },
        {
          "id":"175",
          "name":null,
          "source":"64",
          "target":"55"
        },
        {
          "id":"183",
          "name":null,
          "source":"64",
          "target":"57"
        },
        {
          "id":"179",
          "name":null,
          "source":"64",
          "target":"58"
        },
        {
          "id":"182",
          "name":null,
          "source":"64",
          "target":"59"
        },
        {
          "id":"181",
          "name":null,
          "source":"64",
          "target":"60"
        },
        {
          "id":"180",
          "name":null,
          "source":"64",
          "target":"61"
        },
        {
          "id":"176",
          "name":null,
          "source":"64",
          "target":"62"
        },
        {
          "id":"178",
          "name":null,
          "source":"64",
          "target":"63"
        },
        {
          "id":"187",
          "name":null,
          "source":"65",
          "target":"48"
        },
        {
          "id":"194",
          "name":null,
          "source":"65",
          "target":"55"
        },
        {
          "id":"193",
          "name":null,
          "source":"65",
          "target":"57"
        },
        {
          "id":null,
          "name":null,
          "source":"65",
          "target":"58"
        },
        {
          "id":"192",
          "name":null,
          "source":"65",
          "target":"59"
        },
        {
          "id":null,
          "name":null,
          "source":"65",
          "target":"60"
        },
        {
          "id":"190",
          "name":null,
          "source":"65",
          "target":"61"
        },
        {
          "id":"188",
          "name":null,
          "source":"65",
          "target":"62"
        },
        {
          "id":"185",
          "name":null,
          "source":"65",
          "target":"63"
        },
        {
          "id":"186",
          "name":null,
          "source":"65",
          "target":"64"
        },
        {
          "id":"200",
          "name":null,
          "source":"66",
          "target":"48"
        },
        {
          "id":"196",
          "name":null,
          "source":"66",
          "target":"58"
        },
        {
          "id":"197",
          "name":null,
          "source":"66",
          "target":"59"
        },
        {
          "id":"203",
          "name":null,
          "source":"66",
          "target":"60"
        },
        {
          "id":"202",
          "name":null,
          "source":"66",
          "target":"61"
        },
        {
          "id":"198",
          "name":null,
          "source":"66",
          "target":"62"
        },
        {
          "id":"201",
          "name":null,
          "source":"66",
          "target":"63"
        },
        {
          "id":"195",
          "name":null,
          "source":"66",
          "target":"64"
        },
        {
          "id":"199",
          "name":null,
          "source":"66",
          "target":"65"
        },
        {
          "id":"204",
          "name":null,
          "source":"67",
          "target":"57"
        },
        {
          "id":null,
          "name":null,
          "source":"68",
          "target":"11"
        },
        {
          "id":null,
          "name":null,
          "source":"68",
          "target":"24"
        },
        {
          "id":"205",
          "name":null,
          "source":"68",
          "target":"25"
        },
        {
          "id":"208",
          "name":null,
          "source":"68",
          "target":"27"
        },
        {
          "id":null,
          "name":null,
          "source":"68",
          "target":"41"
        },
        {
          "id":"209",
          "name":null,
          "source":"68",
          "target":"48"
        },
        {
          "id":"213",
          "name":null,
          "source":"69",
          "target":"11"
        },
        {
          "id":"214",
          "name":null,
          "source":"69",
          "target":"24"
        },
        {
          "id":"211",
          "name":null,
          "source":"69",
          "target":"25"
        },
        {
          "id":null,
          "name":null,
          "source":"69",
          "target":"27"
        },
        {
          "id":"217",
          "name":null,
          "source":"69",
          "target":"41"
        },
        {
          "id":"216",
          "name":null,
          "source":"69",
          "target":"48"
        },
        {
          "id":"212",
          "name":null,
          "source":"69",
          "target":"68"
        },
        {
          "id":"221",
          "name":null,
          "source":"70",
          "target":"11"
        },
        {
          "id":"222",
          "name":null,
          "source":"70",
          "target":"24"
        },
        {
          "id":"218",
          "name":null,
          "source":"70",
          "target":"25"
        },
        {
          "id":"223",
          "name":null,
          "source":"70",
          "target":"27"
        },
        {
          "id":"224",
          "name":null,
          "source":"70",
          "target":"41"
        },
        {
          "id":"225",
          "name":null,
          "source":"70",
          "target":"58"
        },
        {
          "id":"220",
          "name":null,
          "source":"70",
          "target":"68"
        },
        {
          "id":"219",
          "name":null,
          "source":"70",
          "target":"69"
        },
        {
          "id":"230",
          "name":null,
          "source":"71",
          "target":"11"
        },
        {
          "id":"233",
          "name":null,
          "source":"71",
          "target":"25"
        },
        {
          "id":"226",
          "name":null,
          "source":"71",
          "target":"27"
        },
        {
          "id":"232",
          "name":null,
          "source":"71",
          "target":"41"
        },
        {
          "id":null,
          "name":null,
          "source":"71",
          "target":"48"
        },
        {
          "id":"228",
          "name":null,
          "source":"71",
          "target":"68"
        },
        {
          "id":"227",
          "name":null,
          "source":"71",
          "target":"69"
        },
        {
          "id":"229",
          "name":null,
          "source":"71",
          "target":"70"
        },
        {
          "id":"236",
          "name":null,
          "source":"72",
          "target":"11"
        },
        {
          "id":"234",
          "name":null,
          "source":"72",
          "target":"26"
        },
        {
          "id":"235",
          "name":null,
          "source":"72",
          "target":"27"
        },
        {
          "id":"237",
          "name":null,
          "source":"73",
          "target":"48"
        },
        {
          "id":"238",
          "name":null,
          "source":"74",
          "target":"48"
        },
        {
          "id":"239",
          "name":null,
          "source":"74",
          "target":"73"
        },
        {
          "id":"242",
          "name":null,
          "source":"75",
          "target":"25"
        },
        {
          "id":"244",
          "name":null,
          "source":"75",
          "target":"41"
        },
        {
          "id":null,
          "name":null,
          "source":"75",
          "target":"48"
        },
        {
          "id":"241",
          "name":null,
          "source":"75",
          "target":"68"
        },
        {
          "id":"240",
          "name":null,
          "source":"75",
          "target":"69"
        },
        {
          "id":"245",
          "name":null,
          "source":"75",
          "target":"70"
        },
        {
          "id":"246",
          "name":null,
          "source":"75",
          "target":"71"
        },
        {
          "id":"252",
          "name":null,
          "source":"76",
          "target":"48"
        },
        {
          "id":"253",
          "name":null,
          "source":"76",
          "target":"58"
        },
        {
          "id":"251",
          "name":null,
          "source":"76",
          "target":"62"
        },
        {
          "id":"250",
          "name":null,
          "source":"76",
          "target":"63"
        },
        {
          "id":"247",
          "name":null,
          "source":"76",
          "target":"64"
        },
        {
          "id":"248",
          "name":null,
          "source":"76",
          "target":"65"
        },
        {
          "id":"249",
          "name":null,
          "source":"76",
          "target":"66"
        }
      ],
      "categories":[
        {
          "name":"类目0"
        },
        {
          "name":"类目1"
        },
        {
          "name":"类目2"
        },
        {
          "name":"类目3"
        },
        {
          "name":"类目4"
        },
        {
          "name":"类目5"
        },
        {
          "name":"类目6"
        },
        {
          "name":"类目7"
        },
        {
          "name":"类目8"
        }
      ],
      "roam":true,
      "label":{
        "normal":{
          "position":"right"
        }
      },
      "lineStyle":{
        "normal":{
          "curveness":0.3
        }
      }
    }
  ]
};