name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
          npm install -g jshint
          npm install git+https://github.com/ecomfe/zrender.git
      - name: build zrender
        run: |
          cd node_modules/zrender
          npm install
          npm run prepublish
          cd ../..
      - name: jshint
        run: |
          jshint
      - name: build release
        run: |
          npm run release
        env:
          CI: true
      - name: unit test
        run: |
          npm run test
